---
output: html_fragment
bibliography: App_References.bib
csl: ama.csl
link-citations: yes
linkcolor: blue
always_allow_html: true
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = "www/")
  })
---

<br>

#### `r shiny::icon("book-open")`  Overview ####  
Matching is used to minimise bias in observational studies prior to estimating a treatment effect. This app aims to provide insights into distance-based matching methods. The four plots to the left reveal what is happening on a match-by-match basis when using the Mahalanobis distance or propensity score to match treated and control units. 
  
The simulated data used to compare matching methods include a treatment indicator variable (`t`), covariates (`X1` and `X2`) and an outcome variable (`y`). In most cases the treatment variable that is used for matching is binary, which is this case for the data available in this app.  

<br>

#### `r shiny::icon("chart-simple")`  Plot 1 and Plot 2 ####  
Plot 1 and 2 show the actual data the matches were performed on. A frame by frame progression of how the matches occurred for two methods specified by the user is shown. The <span style="color:#3772ff; font-weight: bold;">blue</span> triangles represent treated individuals and <span style="color:#df2935; font-weight: bold;">red</span> triangles represented untreated or control individuals. When matching occurs, every treated unit is paired with a control.  
  
<br>

#### `r shiny::icon("chart-simple")` Plot 3 - Standardised Mean Difference ####   
Plot 3 shows the Standardised Mean Difference (SMD) between each of the covariates for the raw values and each of the matching methods. Each frame shows the updated SMD for the matched data in Plot 1 and Plot 2 based on the matches made up until that point. Note that the raw SMD does not change because the underlying data does not change.  
  
<br>
  
#### `r shiny::icon("chart-simple")` Plot 4 - Estimates of the Treatment Effect ####  
Plot 4 shows the estimates of the treatment effect for:  
-   the unadjusted linear regression (raw estimate)  
-   the two pre-specified matching methods  
-   the actual treatment effect (only applicable in simulated data)  

The user can optionally overlay estimates based on other applications of the distance metric, which do not involve matching:
-   propensity score stratification  
-   propensity score weighting  

The cumulative effect of the estimates as units are added to the data is also visible in relation to the matches seen in Plot 1 and 2. The formula and the treatment effect used to simulate the outcome is the same for all methods.  
  
