---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(MatchIt)
library(cem)
library(ggpubr)
library(cobalt)
library(optmatch)
```




```{r}
mo1 <- match_on(treat~educ+age, data = lalonde, method = "mahalanobis") 

mo2 <- match_on(psm$fitted.values, z=lalonde$treat) 

identical(mo1,mo2)

view(mo2@.Data)

#%>% unique() 

m.out1 <- pairmatch(mo1, data=lalonde)

d.m.out1 <- data.frame(lalonde, matches = m.out1, check.rows = T)

summary(m.out1)

psm <- glm(treat~educ+age, family= "binomial", data = lalonde)

# mo2 <- match_on(treat ~ psm, data = lalonde) #%>% unique() 

m.out2 <- pairmatch(psm, data=lalonde)

d.m.out2 <- data.frame(lalonde, matches = m.out2, check.rows = T)

# attributes(d.m.out2$matches)

# ggplot(d.m.out1, aes(educ, age, color = as.factor(treat))) + 
#   geom_point(alpha = 0.5) 

ggplot(d.m.out1[!is.na(d.m.out1$matches),], 
       aes(educ, age, color = as.factor(treat))) + 
    geom_point(alpha = 0.5) + 
    geom_line(aes(group = matches), alpha = 0.5, color="grey50") +
    lims(y=c(min(d.m.out1$age),max(d.m.out1$age)), 
         x= c(min(d.m.out1$educ),max(d.m.out1$educ)))


ggplot(d.m.out2, aes(educ, age, color = as.factor(treat))) +
    geom_point(alpha = 0.5)

ggplot(d.m.out2[!is.na(d.m.out2$matches),], 
       aes(educ, age, color = as.factor(treat))) + 
    geom_point(alpha = 0.5) + 
    geom_line(aes(group = matches), alpha = 0.5, color="grey50") +
    lims(y=c(min(d.m.out1$age),max(d.m.out1$age)), 
         x = c(min(d.m.out1$educ),max(d.m.out1$educ)))


# d.m.out2 %>% as.data.frame() %>% group_by(matches) %>% summarise(n = n())
# 
# stringi::stri_replace_all_fixed(d.m.out1$matches, "1.", "") %>% as.numeric()
# 
# mo1["1","269"]
# 
# which.min(mo1[1,])
# 
# dim(mo1)

# d.m.out1 %>% group_by(treat, matches) %>% rownames()

inner_join(d.m.out1, d.m.out1, by = c("matches" = "matches"), suffix=c("",".y")) %>% filter(treat != treat.y)

rm(d.r.names)
d.r.names <- d.m.out1 %>% filter(treat==1 & is.na(matches)==F) %>% 
  arrange(matches) %>% mutate(treated=rownames(.), m.order=stringi::stri_replace_all_fixed(matches, "1.", "") %>% as.numeric()) %>% 
  select(treated, matches, m.order) %>%
  cbind(untreated=d.m.out1 %>% filter(treat==0 & is.na(matches)==F) %>% 
          arrange(matches) %>% rownames()) %>% arrange(m.order)

# rownames(d.r.names) <- d.r.names[,1]


# d.m.out1$matches %>% stringi::stri_replace_all_fixed("1.", "") %>% as.numeric()

cbind(d.r.names, dist=mo1[as.matrix(d.r.names[c("treated","untreated")])])


```


```{r}

dist.matches <- function(d.m, order="data", replace=FALSE, inc.equ=FALSE){
  
  order <- switch(order,
                "largest" = order(apply(d.m,1,min), decreasing = T),
                "smallest" = order(apply(d.m,1,min)),
                "random" = sample(seq_along(d.m[,1]), nrow(d.m), 
                                  replace = FALSE),
                "data" = seq_along(d.m[,1]))
  
  ids <- list(treatment=NA, control=NA, dist=NA) %>% as.data.frame()
  
  if (replace) inc.equ <- FALSE
  
  for (i in order) {
      
      if (replace) {
        d <- d.m[i,]
      } else {
        d <- d.m[i,!colnames(d.m) %in% ids$control]
      }
      
      if (inc.equ) {
        nms <- names(which(d==min(d)))
        a <- list(treatment = rep(as.character(i), length(nms)), 
                  control = nms, 
                  dist = rep(min(d), length(nms)))
      } else {
        a <- list(treatment = as.character(i), 
                  control = names(which.min(d)), 
                  dist = min(d))
      }
    
      ids <- rbind(ids,a)
      
  }
  
  ids <- ids[-1,]
  rownames(ids) <- 1:nrow(ids)
  
  return(ids)
}

# mo1[1,which(mo1[1,]==min(mo1[1,]))]
# 
# mapply(`[[`, dimnames(mo1), a)
# 
# order(apply(mo1,1,min))
# 
# ids
# 
# names(mo1[,1])
# dimnames(mo1)
# 
# names(d)
# 
# dim(mo1[!rownames(mo1) %in% ids$treatment, 
#              !colnames(mo1) %in% ids$control])
# 
# 
# ids$control %>% unique()
# 
# seq_len(mo1)
# 
# order(mo1, decreasing = T)
# 
# dist.matches(mo1)# %>% arrange(control)
# 
# mo1[2,]
# nms <- names(which(mo1[113,]==min(mo1[113,])))
# list(rep(113, ), names(which(mo1[113,]==min(mo1[113,]))), min(mo1[113,]))




```



```{r}

mtch <- dist.matches(mo1, order = "smallest", replace=T)

mtch <- rbind(list(ob=mtch$treatment, dist=mtch$dist, grp=mtch$treatment) %>%
                as.data.frame(), 
              list(ob=mtch$control, dist=mtch$dist, grp=mtch$treatment) %>%
                as.data.frame())

mtch %>% group_by(ob) %>% mutate(weights=1/n(), min.dist=min(dist))

rownames(mtch) <- mtch$ob



match.out <- merge(lalonde, mtch, by=0, all.x = T)


ggplot(match.out, aes(educ,age, color=as.factor(treat))) + geom_point() +
  geom_line(aes(group=grp))



```


```{r}
weights.subclass <- function(psclass, treat, estimand = "ATT") {

  NAsub <- is.na(psclass)

  i1 <- treat == 1 & !NAsub
  i0 <- treat == 0 & !NAsub

  weights <- setNames(rep(0, length(treat)), names(treat))

  if (!is.factor(psclass)) {
    psclass <- factor(psclass, nmax = min(sum(i1), sum(i0)))
    levels(psclass) <- seq_len(nlevels(psclass))
  }

  treated_by_sub <- setNames(tabulate(psclass[i1], nlevels(psclass)), levels(psclass))
  control_by_sub <- setNames(tabulate(psclass[i0], nlevels(psclass)), levels(psclass))

  total_by_sub <- treated_by_sub + control_by_sub

  psclass <- as.character(psclass)

  if (estimand == "ATT") {
    weights[i1] <- 1
    weights[i0] <- (treated_by_sub/control_by_sub)[psclass[i0]]

    #Weights average 1
    weights[i0] <- weights[i0]*sum(i0)/sum(weights[i0])
  }

  return(weights)
}

exactify

```



```{r}

psm <- glm(treat~educ+age, family= "binomial", data = lalonde)

mo1 <- match_on(psm) 

mo2 <- match_on(psm$fitted.values, z=lalonde$treat) 

identical(mo1,mo2)

dm1 <- dist.matches(mo1, order = "smallest", replace=T)
dm2 <- dist.matches(mo2, order = "smallest", replace=T)

identical(dm1,dm2)

all.equal(
dm1 %>% arrange(treatment)# %>% select(treatment, control)#,=
dm2 %>% arrange(treatment)# %>% select(treatment, control)
)

lalonde[c("8","192", "458"),]


mo1["8",]
mo2["8",]


```

```{r}



```

