---
title: "PSM-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PSM-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}

create.sim1.data()

ggplot(create.sim1.data(), aes(X1, X2, color=t, group = t)) + geom_point() + geom_smooth(formula=y~x,method = "glm", fullrange=T)


table(create.sim3.data(rho=-1)$t)
```


```{r}

    n = 100
    means = c(0,0)
    sd1 = 1
    sd2 = 2
    rho = .3

    # Generating t
    weight_t1 = 0.5
    weight_t2 = 0.5

    # Generating y
    weight_y0 = 2
    weight_y1 = 1
    weight_y2 = -1
    te = 2 # True treatment effect

  varcovarMat <- matrix(c(sd1^2, sd1*sd2*rho, sd1*sd2*rho, sd2^2),2)

  # noise <- rnorm(n, 0, 2) # random noise

  # data.frame(MASS::mvrnorm(n, mu = means, Sigma = varcovarMat))
  data.frame(MASS::mvrnorm(n, mu = means, Sigma = varcovarMat)) %>%
  mutate(t=rbinom(n, 1, prob = arm::invlogit(weight_t1*X1 + weight_t2*X2)))
  
  for (i in 1:10){
  df <- data.frame(MASS::mvrnorm(n, mu = means, Sigma = varcovarMat)) %>%
    mutate(t = rbinom(n, 1, prob = arm::invlogit(weight_t1*X1 + weight_t2*X2)),
           y = weight_y0 + te*t + weight_y1*X1 + weight_y2*X2)
  
  check <- df$t %>% table()
  
  print(check[[2]]<=50)
  }

table(df$t)[[2]]

```

```{r}

count <- c(n=0,tr=0,untr=0)
 
for (i in -1000:1000){
  j <- i * 0.1
  # print(i)
  a <- create.sim3.data(n=200,rho = 1, weight_t2 = i) %>% select(t) %>% table()
  
  count <- rbind(count,c(i,a))
  # p <- ggplot(a, aes(X1,X2,color=t)) + geom_point() + ylim(-5,5) + xlim(-5,5)
  # print(p)
}

count <- count %>% data.frame()

ggplot(count, aes(n,tr-untr)) + geom_point()# + geom_point(aes(n,X2))
       
```


```{r}

# matrix(c(sd1^2, sd1*sd2*rho, sd1*sd2*rho, sd2^2),2)

create.sim3.data()

```


```{r}
# set.seed(6)
# rm(.Random.seed, envir=globalenv())
d <- create.sim2.data(te=4, 0,5,3,-2)

leg.g <- guide_legend("Groups")

p1 <- ggplot(d, aes(X1, X2, colour=t.char)) + geom_point() + 
  ggforce::geom_mark_rect(aes(fill=t.char)) +
  guides(colour=leg.g,fill=leg.g)

p2 <- ggplot(d, aes(X1,X2,color=y)) + geom_point() + 
  scale_color_continuous(type="viridis")

ggpubr::ggarrange(p1,p2,ncol = 1)

  
d <- create.sim1.data(5)

p1 <- ggplot(d, aes(X1, X2, colour=t.char)) + geom_point() + 
  ggforce::geom_mark_rect(aes(fill=t.char)) + 
    guides(colour=leg.g,fill=leg.g)
p2 <- ggplot(d, aes(X1,X2,color=y)) + geom_point() + 
  scale_color_continuous(type="viridis")

ggpubr::ggarrange(p1,p2,ncol = 1)

  
d <- create.sim3.data()

# p3 <- 
p1 <-  ggplot(d, aes(X1, X2, colour=t.char)) + geom_point() + 
  ggforce::geom_mark_hull(aes(fill=t.char)) +
  guides(colour=leg.g,fill=leg.g)
  
p2 <- ggplot(d, aes(X1,X2,color=y)) + geom_point() + 
  scale_color_continuous(type="viridis")


ggpubr::ggarrange(p1,p2,ncol = 1)
```

```{r}

d <- create.sim1.data(5)
# d <- create.sim2.data(te=4, 0,5,3,-2)
# d <- create.sim3.data(weight_t1=-1,weight_t2=-2, sd1=10, sd2=20)


ggpubr::ggarrange(
  ggplot(d, aes(X1, X2, colour=t.char)) + geom_point(alpha=0.5) +
    guides(colour=guide_legend("Groups")),
  ggplot(d, aes(t.char, y, fill=t.char)) + geom_boxplot() + 
    xlab("Groups"),
  ggplot(d, aes(X1, y, colour=t.char)) + geom_point(alpha=0.5) + 
    guides(colour=guide_legend("Groups")),
  ggplot(d, aes(X2, y, colour=t.char)) + geom_point(alpha=0.5) +
    guides(colour=guide_legend("Groups")), 
  ncol=2, nrow=2, common.legend = T, legend = "right")
# create.sim3.data(weight_t1=-1,weight_t2=-2, sd1=10, sd2=20)

```


```{r}

p1 <- d %>% ggplot(aes(X1, X2, colour=t.char)) +
         geom_point(alpha=0.5) +
         guides(colour=guide_legend("Groups")) #%>%
  # ggplotly(p)
         
# p2 <- d %>% ggplot(aes(t.char, y, fill=t.char)) + 
#   geom_boxplot() + #theme(legend.position = "none") + 
#   xlab("Groups")
# 
# p3 <- d %>% ggplot(aes(X1, y, colour=t.char)) +
#   geom_point(alpha=0.5) #+ theme(legend.position = "none")
# # +
# #   guides(colour=guide_legend("Groups"))
# 
# p4 <- ggplot(d, aes(X2, y, colour=t.char)) +
#   geom_point(alpha=0.5) #+ theme(legend.position = "none")
# # +
# #   guides(colour=guide_legend("Groups"))

p1 <- ggplotly(p1) %>% layout(showlegend = FALSE,
      xaxis = list(title=list(#font=list(family="Arial Black"),
                   # text="X2",
                   standoff=0)),
      yaxis = list(title=list(#font=list(family="Arial Black"),
                   # text="X2",
                   standoff=0)))
p1

subplot(p1,p2,p3,p4,widths = c(0.47,0.47), 
        heights = c(0.45,0.45),
        margin = 0.05, shareX = F, shareY = F, nrows = 2,
        titleX = T, titleY = T)

# ncol=2, nrow=2, common.legend = T, legend = "right")

```



```{r}
d <- create.sim2.data(2)
f <- t~X1+X2

p <- matched.data(f, d, "Propensity Score", "data", T)

m <- matched.data(f, d, "Mahalanobis", "data", T)
# matching.plot(m, "X1", "X2", "t", F)
# matching.plot(p, "X1", "X2", "t", F)

# ply <- 
  # suppressWarnings(
    combined.plot(xvar="X1", yvar="X2", M1=m, M2=p, te=5,
                  outcome=y~t+X1+X2 )#)

# ply
  
matching.plot(p,"X1","X2", F)

p$matched.data[["pair.dist"]]

m.data <- data.frame(
    x=p$matched.data[["X1"]],
    y=p$matched.data[["X2"]],
    t=factor(p$matched.data[["t"]]),
    subclass=p$matched.data[["subclass"]],
    pair.dist=p$matched.data[["pair.dist"]],
    t.char=ifelse(p$matched.data[["t"]]==0,"Control","Treated")) %>%
    mutate(text=paste0(t.char, "<br>Pair number: ", subclass,
                               "<br>", "X1",": ", round(x,3),
                               "<br>", "X2", ": ", round(y,3))) %>%
    arrange(pair.dist, subclass) %>%
    mutate(ord=(row_number(pair.dist) + (row_number(pair.dist)%%2))/2)



```


```{r}

  d1 <- accumulate_by(p$matched.data, ~ord) %>%
    mutate(rframe=max(frame)-frame)

  treatment <- p$treatment
  max.match <- max(d1$rframe)

  test <- lm(y~t+X1+X2,d1[d1$rframe==1,])
  
  coef(test)[[treatment]]
  
  a <- lapply(1:max.match, function(x) {
    m1 <- lm(y~t+X1+X2, d1[d1$rframe==x,])

    return(c(distance=p$distance,
                 idx=x,
                 estimate=coef(m1)[[treatment]]))#,
                 # confint(m))[treatment,])
  }  ) %>% bind_rows()# unlist() #
  #%>% 
    
    a <- a %>% mutate(across(idx:estimate, as.numeric)) %>%
    mutate(txt=paste0("Estimate: ", round(estimate,3)))

  for (x in 1:nrow(a)) {
    if (is.na(a[x,4]))
    {a[x,4] <- a[x,3]}

    if (is.na(a[x,5]))
    {a[x,5] <- a[x,3]}
  }

dt <- create.sim1.data()
    
dt.m <- matched.data(t~X1+X2, dt, dist = "Propensity Score")

get.estimates(dt.m, y~t+X1+X2)

mod <- lm(y~t+X1+X2, dt.m$data, weights = dt.m$wt.ATT)

coef(mod)[["t"]]

o.f <- y~t+X1+X2 
all.vars(o.f)[-1]


x <- create.sim1.data(2)
y <- create.sim2.data(2)

all(x==y)


if(length(all.equal(x,y))>1) FALSE else TRUE

length(all.equal(x,y))
```

```{r}


f <- y~t+X1+X2
d <- p$data
  #raw
  mod.v <- lm(f, d)
  raw <- coef(mod.v)[[treatment]]
    # cbind(estimate=coef(mod.v),confint(mod.v))[treatment,]

  #weighted
  mod.w <- lm(f, d, weights = p$wt.ATT)
  weighted <- coef(mod.w)[[treatment]]
  # cbind(estimate=coef(mod.w),
  #                   confint(mod.w))[treatment,]

  #stratified
  max.strat <- max(as.numeric(p$stratification))

  stratified <- lapply(1:max.strat, function(x) {
    m <- lm(f, d[p$stratification==x,])

    return(coef(m)[[treatment]])
                 # confint(m))[treatment,])
  }  ) %>% unlist() %>% mean(na.rm=T)

  a <- rbind(raw, weighted, stratified) %>% as.data.frame()

  colnames(a) <- c("estimate")#, "CI_2.5", "CI_97.5")

  a$method <- rownames(a)

  b <- a[,1] %>% t() %>% as.data.frame()

  colnames(b) <- rownames(a)

  b <- cbind(n=1:(nrow(p$pairs)-1),b)


```



```{r}
library(dplyr)

comb.match.ests <- rbind(
matching.ests(p,"y") %>% mutate(method=paste0("Method 1 - ",distance)),
matching.ests(m,"y") %>% mutate(method=paste0("Method 2 - ",distance))
)

comb.match.ests.cum <- comb.match.ests %>%
            accumulate_by(~idx-1) %>% select(-rframe) %>%
            mutate(rframe=frame)

gg4 <- ggplot(comb.match.ests.cum,
         aes(idx, estimate, linetype=method, group=method,
             frame=frame, colour=method,
             text=paste0(method, " Estimate: ", estimate)
             )) + geom_line(size=1)

  gg4 <- ggplotly(gg4, tooltip = "text") %>%
    animation_opts(transition = 0, redraw=F, frame=400)# %>%

  # gg4 <- plot_ly(comb.match.ests.cum, frame=~rframe) %>%
  #         add_lines(x=~idx, y=~estimate, linetype=~distance, text=~distance,
  #                   hovertemplate="%{text} Estimate: %{y}<extra></extra>")

    # layout(showlegend = FALSE, #hovermode = "x unified",
    #        xaxis = axis.settings("n observations"),
    #        yaxis = axis.settings("Estimate of Treatment Effect", y.range, F)
    # )
  
gg4

any(round(runif(100000,0.51,3.49))>3)
```



```{r}

a <- cbind(get.estimates(m, "y"), te=2)

b <- matching.ests(m, "y")

c(min(c(b[['estimate']],a[1,2:4] %>% unlist())),
max(c(b[['estimate']],a[1,2:4] %>% unlist())))

comb.match.ests.cum

matching.ests(p, "y") %>%
      mutate(method=paste0("Method 1 - ",distance),
             txt=paste0(method, " Estimate: ", round(estimate,3)))

```



```{r}

xvar <- "X1"
yvar <- "X2"
tvar <- "t"
mdist <- m$distance

  all.data <- data.frame(x=m$data[[xvar]],
                         y=m$data[[yvar]],
                         t=factor(m$data[[tvar]])) %>% 
                mutate(t.char=ifelse(t==0,"Control","Treated"))


  m.data <- data.frame(
    x=m$matched.data[[xvar]],
    y=m$matched.data[[yvar]],
    t=factor(m$matched.data[[tvar]]),
    subclass=m$matched.data[["subclass"]],
    pair.dist=m$matched.data[["pair.dist"]]) %>%
    arrange(pair.dist, subclass) %>%
    mutate(t.char=ifelse(t==0,"Control","Treated"),
           ord=(row_number(pair.dist) + (row_number(pair.dist)%%2))/2)

  d.ann <- m.data %>% mutate(distance = mdist, rframe=max(ord)-ord)

  d <- accumulate_by(m.data, ~ord) %>% mutate(distance = mdist)

  # gp <- ggplot(d, aes(x=x, y=y, group=subclass, frame=rframe)) +
  #   geom_point(aes(color=t.char, shape=t.char), alpha=0.5, size=3) +
  #   geom_line() +
  #   geom_point(data=d.ann, aes(color=t.char),
  #              size = 5, stroke = 2, shape=21, alpha=0.5) +
  #   scale_color_manual(values=c(0,1),
  #                      palette=colorRampPalette(c("red", "blue"))) +
  #   scale_shape_manual(values = c(2,6))


  # pltly <- plot_ly(d, frame=~rframe) %>%
  #           add_trace(x=~x, y=~y, type="scatter", mode="markers",
  #                     marker=list(size=10,line=list(width=1.5)),
  #                     symbol= ~t, symbols = c('105','106'),
  #                     color=~t, colors = c("red","blue"),
  #                     line=list(color="grey"),
  #                     split=~subclass, showlegend=F
  #                     ) %>%
  # add_markers(x=~x, y=~y, color=~t,
  #        colors = c("red","blue"), #size = 10, linewidth=1.5,
  #        marker=list(size=10,line=list(width=1.5)),
  #        symbol= ~t, symbols = c('105','106')
  #        ) %>%
  # add_paths(split=~subclass, x=~x, y=~y) %>%
  # # add_lines(split)
  #           add_markers(data=all.data,
  #               x=~x, y=~y,
  #               type = 'scatter',
  #               mode = 'markers',
  #               marker = list(alpha = 0.5, size = 10, color="#A9A9A9"),
  #               symbol= ~t.char,
  #               symbols = c('105','106'),
  #               inherit = F) %>%
  #           animation_opts(transition = 0, redraw=T, frame=400)
  # 
  pltly
  
  # pltly <- pltly %>%
  #           add_lines(data=d.ann, x=~x, y=~y, color=~t,
  #               colors=colorRampPalette(c("red", "blue")),
  #               symbol= ~t, symbols = c('105','106'))

```


```{r}

 # geom_line(aes(y = Illiteracy, colour = "Illiteracy Rate", 
 #                text = paste(State, '<br>Murder Rate:', Murder, '<br>Illiteracy:', Illiteracy),
 #                group=1))+

  gp <- ggplot(d, aes(x=x, y=y, group=subclass, frame=rframe)) +
    geom_point(aes(color=t, shape=t,
                   text=paste0(t.char, "<br>Pair number: ", subclass,
                              "<br>", xvar,": ", round(x,3),
                              "<br>", yvar, ": ", round(y,3)) 
                   ), size=3, stroke=1) +
    geom_line() +
    geom_point(data=d.ann, aes(color=t),
               size = 5, stroke = 2, shape=21, alpha=0.5) +
    scale_color_manual(values=c(0,1),
                       palette=colorRampPalette(c("red", "blue"))) +
    scale_shape_manual(values = c(2,6))

  pltly <- ggplotly(gp, tooltip = 'text')  %>% 
    add_markers(data=all.data, x=~x, y=~y, text=~t.char,
                color=~t, colors=c("pink","lightblue"),
                marker = list(alpha = 0.5, size = 10,line=list(width=1.5)),
                symbol= ~t, symbols = c('105','106'),
                hovertemplate = glue::glue("%{{text}}<br>{xvar}: %{{x:.3f}}<br>{yvar}: %{{y:.3f}}<extra></extra>"),
                inherit = F) %>%
    layout(showlegend = FALSE,
           xaxis = axis.settings(xvar),
           yaxis = axis.settings(yvar)) %>%
    animation_opts(transition = 0, redraw=T, frame=400)
  
  pltly
```


```{r}


test <- function(

    # Generating X1 and X2
    n = 200,
    mean1 = 0,
    mean2 = 0,
    sd1 = 1,
    sd2 = 1,
    rho = .3, #must be between -1 and 1 inclusive.

    # Generating t
    weight_t1 = 0.5, #effect of X1 on t, -10 to 10
    weight_t2 = 0.5,  #effect of X2 on t, -10 to 10

    # Generating y
    weight_y0 = 2, #base value of y
    weight_y1 = 1, #effect of X1 on y, -10 to 10
    weight_y2 = -1, #effect of X2 on y, -10 to 10
    te = 2 # True treatment effect, -10 to 10
){

  means = c(mean1,mean2)

  varcovarMat <- matrix(c(sd1^2, sd1*sd2*rho, sd1*sd2*rho, sd2^2),2)

  for (i in 1:1000) {
    #create the data
    df <- data.frame(MASS::mvrnorm(n, mu = means, Sigma = varcovarMat)) %>%
      mutate(scaledX1 = scale(X1), scaledX2 = scale(X2),
             t = rbinom(n, 1, 
                        prob = arm::invlogit(weight_t1*scaledX1 + weight_t2*scaledX2)),
             y = weight_y0 + te*t + weight_y1*X1 + weight_y2*X2,
             t.char = ifelse(t==0,"Control","Treated"))

    #only return if there are no more than half of the units "treated"
    if(table(df$t)[[2]]<=(n/2)) return(df)

  }
}


d <- test(mean1 = 10, mean2 = 50, sd1 = 33, sd2=10)

```



```{r}
te<-2
val<-5
o.X1<-5-1
o.X2<-5-3
create.sim2.data(te,0,val,o.X1,o.X2) %>% 
  ggplot(aes(X1,X2, color=t.char)) + geom_point()
```


```{r}

 M1.ests <- matching.ests(m, "y") %>%
    mutate(method=paste("Method 1 -", distance),
                        lab=paste(method,txt))

  M2.ests <- matching.ests(p, "y") %>%
    mutate(method=paste("Method 2 -", distance),
           lab=paste(method,txt))

  comb.match.ests <- rbind(M1.ests, M2.ests)
    # matching.ests(M1, outcome) %>%
    #   mutate(method=paste0("Method 1 - ",distance)),
    # matching.ests(M2, outcome) %>%
    #   mutate(method=paste0("Method 2 - ",distance),
    #          txt=paste0(method, " Estimate: ", round(estimate,3)))
    # )

  comb.match.ests.cum <- comb.match.ests %>%
    accumulate_by(~idx-1) %>% select(-rframe) %>%
    mutate(rframe=frame)

  agg.ests <- cbind(get.estimates(m, "y"), te=2)

```



```{r}
gg4 <- ggplot(comb.match.ests.cum,
         aes(idx, estimate, frame=rframe, group=method, colour=method,
             linetype=method, text=lab
             )) + geom_line(size=1)

  gg4 <- ggplotly(gg4, tooltip = "text") %>%
    animation_opts(transition = 0, redraw=T, frame=400)
  
  
  gg4 <- gg4 %>%
    add_lines(data=agg.ests, x=~n, y=~raw, inherit = F,
              name = "Raw Estimate",
              hovertemplate="Raw Estimate: %{y:>-0,.2f}<extra></extra>") %>%
    add_lines(data=agg.ests, x=~n, y=~weighted, inherit = F,
              name = "Weighted Estimate",
              hovertemplate="Weighted Estimate: %{y:>-0,.2f}<extra></extra>") %>%
    add_lines(data=agg.ests, x=~n, y=~stratified, inherit = F,
              name = "Stratified Estimate",
              hovertemplate="Stratified Estimate: %{y:>-0,.2f}<extra></extra>") %>%
    add_lines(data=agg.ests, x=~n, y=~te, inherit = F,
              name = "True Estimate",
              hovertemplate="True Estimate: %{y:>-0,.2f}<extra></extra>") 
    

  
  gg4
```


```{r}


# Generating X1 and X2
# test <- function(

    # Generating X1 and X2
    n = 200
    mean1 = 0
    mean2 = 0
    sd1 = 1
    sd2 = 1
    rho = .3 #must be between -1 and 1 inclusive.

    # Generating t
    weight_t1 = 0.5 #effect of X1 on t, -10 to 10
    weight_t2 = 0.5  #effect of X2 on t, -10 to 10

    # Generating y
    weight_y0 = 2 #base value of y
    weight_y1 = 1 #effect of X1 on y, -10 to 10
    weight_y2 = -1 #effect of X2 on y, -10 to 10
    te = 2 # True treatment effect, -10 to 10
# ){

  means = c(mean1,mean2)

  varcovarMat <- matrix(c(sd1^2, sd1*sd2*rho, sd1*sd2*rho, sd2^2),2)

  df <- data.frame(MASS::mvrnorm(n, mu = means, Sigma = varcovarMat),t=rbinom(n,1,0.5)) 
  
  df <- df %>% mutate(X1 = X1 + weight_t1 * t, X2 = X2 + weight_t2 * t,
                y = weight_y0 + te*t + weight_y1*X1 + weight_y2*X2,
             t.char = ifelse(t==0,"Control","Treated"))
  
  
  
  # rbinom(n,1,0.5)
  
  #%>%
    
  
  # for (i in 1:1000) {
  #   #create the data
  #   df <- data.frame(MASS::mvrnorm(n, mu = means, Sigma = varcovarMat)) %>%
  #     mutate(scaledX1 = scale(X1), scaledX2 = scale(X2),
  #            t = rbinom(n, 1,
  #                       prob = arm::invlogit(weight_t1*scaledX1 + weight_t2*scaledX2)),
  #            y = weight_y0 + te*t + weight_y1*X1 + weight_y2*X2,
  #            t.char = ifelse(t==0,"Control","Treated")) %>%
  #     select(-c(scaledX1,scaledX2))
  # 
  #   #only return if there are no more than half of the units "treated"
  #   if(table(df$t)[[2]]<=(n/2)) return(df)
  # 
  # }
# }

  
  
ggpubr::ggarrange(
  ggplot(df, aes(X1, X2, colour=t.char)) + geom_point(alpha=0.5) +
    guides(colour=guide_legend("Groups")),
  ggplot(df, aes(t.char, y, fill=t.char)) + geom_boxplot() + 
    xlab("Groups"),
  ggplot(df, aes(X1, y, colour=t.char)) + geom_point(alpha=0.5) + 
    guides(colour=guide_legend("Groups")),
  ggplot(df, aes(X2, y, colour=t.char)) + geom_point(alpha=0.5) +
    guides(colour=guide_legend("Groups")), 
  ncol=2, nrow=2, common.legend = T, legend = "right")
  
```


```{r}
# library(htmlTable)

M.list <- list(
# labs=c("Function","Distance", "Order", "Replacement", "Treatment Effect"),
M1=c("t ~ X1 + X2", "Mahalanobis", "data", T, 5),
M2=c("t ~ X1 + X2", "Propensity Score", "data", F, 5)) %>% as.data.frame()

labs <- c("Function","Distance", "Order", "Replacement", "Treatment Effect")

# setHtmlTableTheme("blank") %>%
# htmlTable(M.list, header=c("Method 1", "Method 2"), rnames=labs) 

rownames(M.list) <- labs

M.list

```

```{r}

lr <- lm(y~t+X1+X2, d)

coef(lr)["t"]

confint(lr)["t",]
```



```{r}
 f<-y ~ t * X1 * X2 * I(X1^2) * I(X2^2) * I(X1^3) * I(X2^3) * I(X1^4) * I(X2^4)

# f <- y ~ t * X1 * X2 * X2^2 * (X1 + X2)^3 * (X1 + X2)^4

t.f <- terms(f)

# attr(t.f, "term.labels") 
attr(t.f, "term.labels")#[stringr::str_detect(attr(t.f, "term.labels"),"t")]

is.null(NULL)

```



```{r}

s.d <- create.sim1.data(2)
d <- NULL

if(is.null(d)) {s.d} else {d}

```



```{r}

tp <- function(d){
  # ggpubr::ggarrange(
  p1 <- ggplot(d, aes(X1, X2, colour=t.char)) +
    geom_point(alpha=0.5) + theme(legend.position = "none") +
    guides(colour="Group")
  p1 <- ggplotly(p1) %>%
    layout(xaxis=list(
      title=list(standoff=0,autorange = TRUE, tickmode="auto")),
      yaxis=list(
        title=list(standoff=0,autorange = TRUE, tickmode="auto")))

  p2 <- ggplot(d, aes(t.char, y, fill=t.char)) + geom_boxplot() +
    xlab("") + theme(legend.position = "none") +
    guides(colour="Group")
  p2 <- ggplotly(p2) %>%
    layout(xaxis=list(
      title=list(standoff=0,autorange = TRUE, tickmode="auto")),
      yaxis=list(
        title=list(standoff=0,autorange = TRUE, tickmode="auto")))

  p3 <- ggplot(d, aes(X1, y, colour=t.char)) + geom_point(alpha=0.5)  +
    theme(legend.position = "none") +
    guides(colour="Group")
  p3 <- ggplotly(p3) %>%
    layout(xaxis=list(
      title=list(standoff=0,autorange = TRUE, tickmode="auto")),
      yaxis=list(
        title=list(standoff=0,autorange = TRUE, tickmode="auto")))
  
  p4 <- ggplot(d, aes(X2, y, colour=t.char)) + geom_point(alpha=0.5)  +
    theme(legend.position = "none") +
    guides(colour="Group")
  p4 <- ggplotly(p4) %>%
    layout(xaxis=list(
      title=list(standoff=0,autorange = TRUE, tickmode="auto")),
      yaxis=list(
        title=list(standoff=0,autorange = TRUE, tickmode="auto")))
  
  return(plotly::subplot(p1,p2,p3,p4, nrows=2, titleX=T, titleY = T,
                         widths = c(0.45,0.45), heights = c(0.45,0.45),
                         margin = 0.1) %>% config(displayModeBar = F)
         )
}

tp(create.sim1.data())

```

```{r}

library(shiny)

shinyApp(
  server = function(input,output,session){},
  ui = fluidPage(
    span(
      "Example",
      div(style = "display:inline-block;",
          title = sd.txt,
          icon("info-circle")))
  )
)

```



```{r}

CR1_BS<-paste("i. This is line 1",
              "ii. This is line 2",
              "iii. This is line 3", sep = "<br>")

sd.txt <- HTML(paste0(strong("Standard Deviation"), br(),
               "Select a value to set the standard deviation for the",
               "normally distributed variables X1 and X2."))


ui <- fluidPage(
  # actionButton("CR1_S1", "Button"),
  fluidRow( icon("question-sign", lib="glyphicon", id="CR1_S1"),

  bsPopover(id="CR1_S1",title=NULL,content=sd.txt ,"right",options = list(container = "body"))
))

server <- function(input, output){}

shinyApp(ui, server)
```


```{r}

sample(c(y~t, y~t+X1, y~t+X2, t~t+X1+X2),1)[1]

paste0(code(deparse1(y~t+X1+X2)))

```


