---
title: "Summary"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Summary}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

The WhatsMatching app provides a simple space for users to gain insights into the matching process through open-ended exploration. Users are able to pair any possible combination of data generation with the matching settings of their choosing, then visualise the matching algorithms unfold, frame-by-frame.

### Highlights

The app has a user-friendly interface that allows users to easily manipulate data and matching settings to see if the outcomes match expectations. Technical jargon has been avoided where possible in favour of plain language descriptions. Hover-overs have been used to give additional information on many of the settings available, without cluttering the main interface.

The main plot interface is clean and intuitive. The interactive `plotly` interface allows users to explore the output of the matching algorithms by zooming, panning, selecting subsets of the data and optionally adding or removing  various plot elements. Tooltips have been used to provide additional information on the plotted data points without overwhelming the user with visual information. A sidebar was added to give meaningful context without intruding on the main interface.

### Limitations

There are some limitations to the features available in the WhatsMatching package and app. Firstly, users are limited to using only Propensity Score or Mahalanobis-based distance matching. This has been a deliberate choice as the frame-by-frame output is most useful to distance-based matching. 

Secondly, the package is only designed for gaining insights into matching in an educational setting, but not for performing statistical analysis with real-world data. However, users may choose to run data through the package first to try and make better decisions about matching for their real analysis.

Thirdly, due to the processing power required to create and render the `plotly` plots, it is not particularly feasible to increase the amount of data used to illustrate matching. To give an example, for a dataset that returns 100 matches there will need to be 5050 rows &times; 2 just to generate the first two plots.

### Future Possibilities

Where to from here? The app is functional and fit for purpose as is, even with the limitations listed above. Considerations for future development may include:

-   Extending the capability of the app to explore other matching methodologies;

-   Increasing the number of dimensions for viewing the matches, for example to include visualisations for matching on multiple variables;

-   Adding the capability to compare different model specifications for estimating the outcome at the same time, rather than having to use the same analysis formula for the two matching mehtods being compared;

-   Adding an option for calliper adjustment (it is just a theoretical option to visualise at the moment).
