---
title: App Information
documentclass: report
output: html_fragment
bibliography: App_References.bib
citation_package: biblatex
csl: ama.csl
link-citations: yes
linkcolor: blue
always_allow_html: true
---
  
The propensity score allows the reduction of a multidimensional space to a single dimension for easy comparison between treated and untreated units. Mathematically, it can be formulated as $e(x_i) = pr(Z_i=1|x)$, where $e(x_i)$ is the propensity score, $Z$ is the treatment variable, $x$ is a vector of covariates, and $i$ represents an individual. Therefore, the propensity score is the probability of receiving treatment given covariates $x$.  
In observational data there is no ability to control which people receive treatment and which do not. In fact, there is often little control over the available covariates that may help inform the outcomes. This potentially exposes observational data to selection bias and confounding. The objective of using the propensity score in data analysis is to replicate a randomised experiment within observational data as a means of bias reduction and covariate balancing. The propensity score can be used in multiple way to achieve this, notably matching, weighting and stratification (aka subclassification).  

#### Weighting  
Weighting with the propensity score differs from matching as no units are pruned from the dataset. This is an advantage over matching in the sense that all data can remain in the analysis, giving the opportunity to calculate the average treatment effect on all units (ATE), as opposed to the ATT.  
  
The formulas for weighting vary depending on the method you want to employ. The data being analysed, by virtue of its source, may be more appropriately analysed for the ATT and not the ATE. The formulas for these weights are:  
$$ATE, w(W,x) = \frac{W}{\hat{e}(x)}+\frac{1-W}{1-\hat{e}(x)}$$  
and    
$$ATE, w(W,x) = W+(1-W)\frac{\hat{e}(x)}{1-\hat{e}(x)}$$  
where $\hat{e}(x)$ indicates the estimated propensity score conditional on observed x covariates.  
  
#### Stratification  
The stratification method varies from matching and weighting in that it relies on the use of the propensity score to group units into quantiles. Once the number of groups has been established, the literature suggests this is between five and ten depending on the size of the dataset5, the treatment effect is estimated across the groups and then averaged to give a mean difference ATE [@guo_propensity_2020].


#### References  
